name: Dependabot Fix

on:
  push:
    branches:
      - dependabot/npm_and_yarn/**

jobs:
  fix:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Fix lockfile
        run: |
          # change directory
          cd .`git log -1 --pretty=%s | awk '{ print $9 }'`

          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock

          # if package.json was not updated, upgrade the dependency
          git diff --name-only HEAD^ HEAD | grep -q 'package.json' || yarn up `git log -1 --pretty=%s | awk '{ print $3 }'`

          # restore package.json from the last commit
          git checkout HEAD -- package.json

          yarn install
        env:
          YARN_ENABLE_SCRIPTS: false # disable postinstall script
          YARN_ENABLE_IMMUTABLE_INSTALLS: false # disable immutable

      - name: Config Git
        run: |
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'

          cd .`git log -1 --pretty=%s | awk '{ print $9 }'` # ditto
          git add yarn.lock .yarn/cache .pnp.*
          git commit -m "Dependabot autofix"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
